---@class SpearConfig
---@field save_path? string Path to save spear list file
---@field prune_missing? boolean Auto-remove files that no longer exist
---@field ui? table UI configuration
---@field ui.border? string Border style: "single", "double", "rounded", "solid", "shadow"
---@field ui.width_ratio? number Window width ratio
---@field ui.height_ratio? number Window height ratio
---@field ui.title? string Window title
